### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by maxbbender** [ThePorcupine/mb-resume#7]
On https://b3nd3r.dev/tagdetail/3 Utilizing is spelt wrong

**Comment by maxbbender** [comment]
More issues with spelling and the J is not underlined. From Will W
https://media.discordapp.net/attachments/165293581798473728/785217235923763240/unknown.png?width=940&height=677

**Comment by maxbbender** [comment]
A generated resume is currently not available due to a bug in wkhtmltopdf related to SSL encyription.

More Spelling error

**Comment by ThePorcupine** [comment]
Fixed
